import {ReminderEditor} from './calendar-reminders';
import {BubbleEntrance} from './bubble-entrance';
import { renderVectorPet } from './pet-vector';
import { layoutPet } from './pet-layout';
import { syncPlacementLabels, syncOnboardingConnections } from './companion-settings';
import settingsHtml from '../index.html?raw';
import overlayHtml from '../overlay.html?raw';
import settingsCss from './styles.css?inline';
import petCss from './pet.css?inline';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as unknown as T;
const settingsFrame=$<HTMLIFrameElement>('settings-frame'),petFrame=$<HTMLIFrameElement>('pet-frame');
const entrance=new BubbleEntrance();let previewAlertSerial=0;
let settings:Document,pet:Document,scene='settings',alertRow:number|null=null,animationStart=0,dragged=false,holding=false,landingUntil=0;
let timerRemaining=0,timerRunning=false,timerDeadline=0;
let reactionUntil=0,reactionPose='tickle',recoveryUntil=0,heat=0,cooldown=0,heldAge=0,pressed=false,lastDraw=0;
function react(pose:string,text:string,duration:number){reactionPose=pose;animationStart=performance.now();reactionUntil=animationStart+duration;recoveryUntil=reactionUntil+1500;get(pet,'pet-menu').hidden=true;get(pet,'pet-reaction').textContent=text;visibility();previewLayout();}
function ticklePet(){if(cooldown>0)return;heat++;if(heat>=3){heat=0;cooldown=6;react('enough','이제 그만!',3000);}else react('tickle','간지러워요!',2200);}

const feedback=(text:string)=>{$('feedback').textContent=text;};
const get=<T extends Element=HTMLElement>(doc:Document,id:string)=>doc.getElementById(id) as unknown as T;
const check=(id:string)=>get<HTMLInputElement>(settings,id).checked;
function frameHtml(html:string,css:string,extra=''){const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('script,link[rel="stylesheet"]').forEach(el=>el.remove());const style=doc.createElement('style');style.textContent=css+'\n'+extra;doc.head.append(style);return '<!doctype html>'+doc.documentElement.outerHTML;}
function tab(name:string){settings.querySelectorAll<HTMLElement>('[data-panel]').forEach(el=>el.hidden=el.dataset.panel!==name);settings.querySelectorAll<HTMLElement>('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===name));}
function showWelcome(show:boolean){get(settings,'onboarding').hidden=!show;get(settings,'app').inert=show;if(show){get(settings,'onboard-mode').hidden=false;get(settings,'onboard-connect').hidden=true;} }
const samples=[['지민 · 디자인팀','@민수 새 온보딩 화면 확인 부탁드려요!','Slack 열기'],['제품팀 주간 미팅','5분 뒤 · 14:00–14:30\n회의 전에 잠깐 숨 돌려볼까요?','일정 열기'],['집중 시간, 잘 마쳤어요!','25분 동안 수고했어요. 이제 잠깐 쉬어가요.',''],['어깨를 쭉 펴볼까요?','50분 동안 열심히 일했어요.\n가볍게 일어나 몸을 풀어주세요.','']];
let previewAnchor={x:195,y:435},previewSize=180,lastResident:boolean|undefined;
const placements={resident:{x:195,y:435,position:'bottom'},alert:{x:195,y:435,position:'bottom'}};
const placementKey=()=>check('pref-resident')?'resident':'alert';
function previewLayout(){layoutPet(pet,previewAnchor,previewSize);}
function visibility(){const resident=check('pref-resident');syncPlacementLabels(resident,settings);if(lastResident!==resident){lastResident=resident;const saved=placements[placementKey()];previewAnchor={x:saved.x,y:saved.y};settings.querySelectorAll<HTMLElement>('[data-pos]').forEach(el=>el.classList.toggle('active',el.dataset.pos===saved.position));previewLayout();}get(pet,'pet-root').hidden=!check('pref-resident')&&alertRow===null&&scene!=='menu'&&performance.now()>=recoveryUntil;}
function alertContent(){if(alertRow===null)return;const [title,body,open]=samples[alertRow]!;get(pet,'title').textContent=check('pref-private_content')?'새 알림이 도착했어요':title!;get(pet,'body').textContent=check('pref-private_content')?'내용을 보려면 해당 앱을 열어주세요.':body!;get(pet,'open').textContent=open!;get(pet,'open').hidden=!open;get(pet,'meeting').hidden=alertRow!==1;get(pet,'snooze').hidden=alertRow!==1&&alertRow!==3;get(pet,'count').textContent=alertRow===0?'1/3':'';get(pet,'next-alert').hidden=alertRow!==0;}
function showScene(next:string){previewAlertSerial++;scene=next;animationStart=performance.now();alertRow=({slack:0,calendar:1,timer:2,stretch:3} as Record<string,number>)[next]??null;get(pet,'bubble').hidden=alertRow===null;get(pet,'pet-menu').hidden=next!=='menu';get(pet,'pet-reaction').hidden=true;showWelcome(next==='welcome');if(next==='settings')tab('companion');alertContent();visibility();previewLayout();document.querySelectorAll<HTMLButtonElement>('[data-scene]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scene===next)));$('scene-title').textContent=({slack:'놓치고 싶지 않은 메시지',calendar:'다음 약속을 챙겨드려요',timer:'집중 끝, 작은 성취 하나',stretch:'잠깐, 몸에도 여유를',menu:'똑띠와 잠깐',welcome:'처음 만나는 작은 동료'} as Record<string,string>)[next]??'작은 동료가 머무는 자리';$('scene-description').textContent=next==='menu'?'클릭하면 간지럽히기, 우클릭하면 타이머와 설정 메뉴를 열어요.':'캐릭터를 우클릭해 메뉴를 열어보세요.';}
const accountStates:Record<string,string>={slack:'off',calendar:'off'};
const accountGeneration:Record<string,number>={slack:0,calendar:0};
function accountState(value:string,only?:string){if(!only)$<HTMLSelectElement>('account-state').value=value;for(const service of only?[only]:['slack','calendar']){accountGeneration[service]=(accountGeneration[service]??0)+1;accountStates[service]=value;const connected=value==='on';get(settings,service+'-status').textContent=value==='error'?'연결이 만료됐어요. 다시 연결해 주세요.':connected?(service==='slack'?'민수 · 똑띠 팀 · 연결됨':'minsu@example.com · 연결됨'):'아직 연결된 계정이 없어요.';const connect=get<HTMLButtonElement>(settings,service+'-connect');connect.disabled=service==='slack'&&connected;connect.textContent=connected?(service==='slack'?'연결됨':'다시 연결'):value==='error'?'다시 연결':service==='slack'?'Slack에 추가하고 연결':'Google Calendar 연결';get(settings,service+'-disconnect').hidden=!connected;const onboardingButton=get<HTMLButtonElement>(settings,service==='slack'?'onboard-slack':'onboard-google');onboardingButton.disabled=connected;onboardingButton.textContent=service==='slack'?'Slack에 추가하고 연결':'Google Calendar 연결';}
syncOnboardingConnections(accountStates.slack==='on',accountStates.calendar==='on',settings);get(settings,'slack-filters').hidden=accountStates.slack!=='on';get(settings,'calendar-refresh').hidden=accountStates.calendar!=='on';get(settings,'calendar-events').innerHTML=accountStates.calendar==='on'?'<li>오늘 14:00 · 제품팀 주간 미팅</li><li>오늘 16:30 · 디자인 리뷰</li>':'';}
function connect(service:string){const generation=(accountGeneration[service]??0)+1;accountGeneration[service]=generation;get(settings,service+'-status').textContent='브라우저에서 계정 연결을 기다리고 있어요…';get(settings,'onboard-status').textContent='연결 과정을 체험하고 있어요…';get<HTMLButtonElement>(settings,service+'-connect').disabled=true;get(settings,service+'-disconnect').hidden=false;setTimeout(()=>{if(accountGeneration[service]!==generation)return;accountState('on',service);get(settings,'onboard-status').textContent='샘플 계정이 연결됐어요.';feedback('샘플 연결 완료 · 실제 계정 인증은 실행하지 않았어요.');},700);}
function tick(){if(timerRunning){timerRemaining=Math.max(0,Math.ceil((timerDeadline-Date.now())/1000));if(!timerRemaining){timerRunning=false;showScene('timer');}}get(settings,'timer-clock').textContent=`${Math.floor(timerRemaining/60).toString().padStart(2,'0')}:${(timerRemaining%60).toString().padStart(2,'0')}`;get(settings,'timer-pause').textContent=timerRunning?'일시정지':'이어서';get<HTMLButtonElement>(settings,'timer-pause').disabled=timerRemaining===0;}
function startTimer(minutes:number){if(!Number.isFinite(minutes)||minutes<1||minutes>1440){feedback('타이머는 1~1440분으로 설정해 주세요.');return;}timerRemaining=Math.round(minutes*60);timerDeadline=Date.now()+timerRemaining*1000;timerRunning=true;tick();react('ack','알겠어요! 시간이 되면 알려드릴게요.',2200);feedback(`${minutes}분 타이머를 미리보기에서 시작했어요.`);}
function setupSettings(){const reminders=new ReminderEditor(settings,()=>feedback('일정 알림 시점을 미리보기에서 변경했어요.'));reminders.render([5]);settings.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab!));get(settings,'companion-status').textContent='미리보기 · 이 화면 안에서만 설정이 바뀝니다.';for(const id of ['pref-resident','pref-hide_fullscreen','pref-hide_presenting','pref-stretch','pref-timer_during_quiet','ov-sound'])get<HTMLInputElement>(settings,id).checked=true;get(settings,'app-version').textContent='0.1.5 · 미리보기';get(settings,'quiet-status').textContent='알림을 받고 있어요';get(settings,'ov-monitor').innerHTML='<option>주 디스플레이 · MacBook / Windows PC</option><option>보조 디스플레이 · 27인치 (샘플)</option>';get(settings,'test-overlay').onclick=()=>showScene('slack');get(settings,'pref-resident').onchange=visibility;get(settings,'pref-private_content').onchange=alertContent;get(settings,'pref-stretch').onchange=()=>{get<HTMLInputElement>(settings,'pref-stretch_minutes').disabled=!check('pref-stretch');};
 for(const id of ['ov-scale','ov-speed']){get(settings,id).oninput=()=>{const value=get<HTMLInputElement>(settings,id).value;get(settings,id+'-val').textContent=Number(value).toFixed(1)+'x';if(id==='ov-scale'){const size=180*Math.min(5,Math.max(.5,Number(value)))/1.7;previewSize=size;previewLayout();}};}
 get(settings,'ov-motion').onchange=()=>{pet.documentElement.classList.toggle('reduce-motion',check('ov-motion'));get<HTMLInputElement>(settings,'ov-speed').disabled=check('ov-motion');get(settings,'ov-speed-row').classList.toggle('disabled',check('ov-motion'));};settings.querySelectorAll<HTMLButtonElement>('[data-pos]').forEach(b=>b.onclick=()=>{settings.querySelectorAll('[data-pos]').forEach(el=>el.classList.toggle('active',el===b));get(settings,'pos-label').textContent=b.title;const pos=b.dataset.pos!;previewAnchor={x:pos.includes('left')?65:pos.includes('right')?pet.defaultView!.innerWidth-65:pet.defaultView!.innerWidth/2,y:pos.includes('top')?180:pos.includes('bottom')?435:300};placements[placementKey()]={...previewAnchor,position:pos};previewLayout();feedback(`출현 위치: ${b.title} · 실제 모니터 이동은 데스크톱 앱에서 적용됩니다.`);});
 get(settings,'onboard-next').onclick=()=>{get(settings,'onboard-mode').hidden=true;get(settings,'onboard-connect').hidden=false;};get(settings,'onboard-back').onclick=()=>{get(settings,'onboard-mode').hidden=false;get(settings,'onboard-connect').hidden=true;};get(settings,'onboard-finish').onclick=()=>{get<HTMLInputElement>(settings,'pref-resident').checked=check('onboard-resident');showScene('settings');feedback('첫 설정을 마쳤어요. 언제든 함께하기에서 바꿀 수 있어요.');};get<HTMLButtonElement>(settings,'onboard-slack').disabled=false;
 for(const service of ['slack','calendar']){get(settings,service+'-connect').onclick=()=>connect(service);get(settings,service+'-disconnect').onclick=()=>accountState('off',service);}get(settings,'onboard-slack').onclick=()=>connect('slack');get(settings,'onboard-google').onclick=()=>connect('calendar');get(settings,'calendar-refresh').onclick=()=>feedback('샘플 일정이 최신 상태예요.');get(settings,'slack-save').onclick=()=>feedback('Slack 필터를 미리보기에 적용했어요.');
 get(settings,'timer-start').onclick=()=>startTimer(Number(get<HTMLInputElement>(settings,'timer-minutes').value));get(settings,'timer-pause').onclick=()=>{timerRunning=!timerRunning;if(timerRunning)timerDeadline=Date.now()+timerRemaining*1000;tick();};get(settings,'timer-cancel').onclick=()=>{timerRunning=false;timerRemaining=0;tick();};for(const min of [0,30,60])get(settings,'quiet-'+min).onclick=()=>{get(settings,'quiet-status').textContent=min?`${min}분 동안 쉬는 중`:'알림을 받고 있어요';feedback(min?`${min}분 조용히 쉬기 · 상태 미리보기`:'알림을 재개했어요.');};
 get(settings,'check-update').onclick=()=>get(settings,'update-status').textContent='최신 버전입니다 · 샘플';get(settings,'diag-view').onclick=()=>{get(settings,'diag-text').textContent='[미리보기 진단 기록]\n앱: 0.1.5\nSlack: 샘플 연결\nGoogle Calendar: 샘플 연결\n실제 장치 정보는 수집하지 않았습니다.';get(settings,'diag-modal').hidden=false;};get(settings,'diag-close').onclick=()=>get(settings,'diag-modal').hidden=true;get(settings,'diag-copy').onclick=()=>feedback('진단 기록 복사 동작 미리보기입니다.');get(settings,'diag-send').onclick=()=>get(settings,'diag-status').textContent='전송 완료 화면 예시 · 실제 전송은 하지 않았어요.';
 settings.querySelectorAll<HTMLInputElement|HTMLSelectElement>('input,select').forEach(el=>el.addEventListener('change',()=>feedback('미리보기에 반영했어요. 실제 앱 설정은 바뀌지 않습니다.')));accountState('off');tick();}
function setupPet(){get(pet,'next-alert').onclick=()=>showScene('calendar');get(pet,'pet-root').hidden=false;get(pet,'pet').oncontextmenu=e=>{e.preventDefault();get(pet,'pet-menu').hidden=!get(pet,'pet-menu').hidden;get(pet,'bubble').hidden=!get(pet,'pet-menu').hidden||alertRow===null;previewLayout();};get(pet,'pet').onclick=()=>{if(!dragged){ticklePet();}};get(pet,'dismiss').onclick=()=>{alertRow=null;get(pet,'bubble').hidden=true;visibility();};for(const id of ['open','meeting','snooze'])get(pet,id).onclick=()=>feedback(id==='snooze'?'5분 뒤 다시 알리는 화면 동작입니다.':id==='meeting'?'실제 앱에서는 회의 링크가 열립니다.':'실제 앱에서는 해당 서비스가 열립니다.');
 pet.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>{get(pet,'pet-menu').hidden=true;switch(b.dataset.action){case 'settings':showScene('settings');break;case 'tickle':ticklePet();break;case 'quiet':get(settings,'quiet-30').click();break;}});get(pet,'pet-timer').onsubmit=e=>{e.preventDefault();startTimer(Number(get<HTMLInputElement>(pet,'pet-minutes').value));get(pet,'pet-menu').hidden=true;};
 const target=get(pet,'pet');let press:{x:number;y:number;anchorX:number;anchorY:number}|null=null;target.onpointerdown=e=>{if(e.button!==0)return;pressed=true;heldAge=0;press={x:e.clientX,y:e.clientY,anchorX:previewAnchor.x,anchorY:previewAnchor.y};dragged=false;target.setPointerCapture(e.pointerId);};target.onpointermove=e=>{if(!press)return;const x=e.clientX-press.x,y=e.clientY-press.y;if(Math.hypot(x,y)>5)dragged=true;if(dragged){holding=true;get(pet,'pet-menu').hidden=true;previewAnchor={x:Math.max(65,Math.min(pet.defaultView!.innerWidth-65,press.anchorX+x)),y:Math.max(180,Math.min(435,press.anchorY+y))};get(pet,'bubble').hidden=true;previewLayout();}};target.onpointerup=target.onpointercancel=()=>{pressed=false;heldAge=0;press=null;if(holding&&check('pref-resident')&&!check('ov-motion')){landingUntil=performance.now()+600;previewAnchor.y=435;}if(holding&&!check('pref-resident'))placements.alert={...previewAnchor,position:'custom'};holding=false;previewLayout();};pet.addEventListener('keydown',e=>{if(e.key==='Escape')get(pet,'pet-menu').hidden=true;});}
function draw(now:number){requestAnimationFrame(draw);if(!pet||!settings)return;
 const dt=lastDraw?Math.min(.1,(now-lastDraw)/1000):0;lastDraw=now;if(!pressed)heat=Math.max(0,heat-dt*.15);cooldown=Math.max(0,cooldown-dt);
 if(pressed&&!dragged){heldAge+=dt;if(heldAge>=.75){heldAge=0;ticklePet();}}else heldAge=0;
 const tickle=now<reactionUntil,landing=now<landingUntil;
 visibility();
 get(pet,'pet-reaction').hidden=!tickle;get(pet,'bubble').hidden=alertRow===null||tickle||holding||landing||!get(pet,'pet-menu').hidden;
 entrance.show(get(pet,'bubble'),alertRow===null?undefined:`preview-${previewAlertSerial}`,check('ov-motion'));
 const pose=holding?'drag':tickle?reactionPose:landing?'land':now<recoveryUntil?'relieved':alertRow!==null?['slack','calendar','timer','stretch'][alertRow]!:'idle';
 get(pet,'sprite').setAttribute('data-preview-pose',pose);
 renderVectorPet(get<SVGSVGElement>(pet,'sprite'),pose,(now-animationStart)*Number(get<HTMLInputElement>(settings,'ov-speed').value),{reduced:check('ov-motion')});
}
async function start(){await Promise.all([new Promise<void>(resolve=>{settingsFrame.onload=()=>{settings=settingsFrame.contentDocument!;resolve();};settingsFrame.srcdoc=frameHtml(settingsHtml,settingsCss,'@media(max-width:540px){.app{grid-template-columns:110px 1fr}.sidebar{padding:12px 8px}.content{padding:18px 12px}.brand{font-size:12px}.row{flex-wrap:wrap;gap:12px}.action-line{flex-wrap:wrap}.welcome-card{padding:22px 14px}.mode-options{grid-template-columns:1fr}}');}),new Promise<void>(resolve=>{petFrame.onload=()=>{pet=petFrame.contentDocument!;resolve();};petFrame.srcdoc=frameHtml(overlayHtml,petCss);})]);setupSettings();setupPet();previewLayout();new ResizeObserver(()=>previewLayout()).observe(pet.body);document.querySelectorAll<HTMLButtonElement>('[data-scene]').forEach(b=>b.onclick=()=>showScene(b.dataset.scene!));$<HTMLSelectElement>('account-state').onchange=e=>{accountState((e.target as HTMLSelectElement).value);showWelcome(false);tab('connections');};$('reset').onclick=()=>location.reload();showScene('settings');feedback('준비됐어요. 위 시나리오 버튼이나 앱 안의 설정을 눌러보세요.');setInterval(tick,250);requestAnimationFrame(draw);}
void start().catch(e=>feedback('미리보기를 불러오지 못했어요: '+String(e)));
